### PR TITLE
Escape newlines via `echo -e` in help rule.

### PR DESCRIPTION
**Pull request by benjamin051000**
Before:
```
kernel-docs/docs ❯ make
\n ------------------------------------------------------------- \n * watch, build and serve the documentation:  make run \n * only build:                                make html \n * only serve:                                make serve \n * clean built doc files:                     make clean-doc \n * clean full environment:                    make clean \n * check links:                               make linkcheck \n * check spelling:                            make spelling \n * check spelling (without building again):   make spellcheck \n * check inclusive language:                  make woke \n * check accessibility:                       make pa11y \n * check style guide compliance:              make vale \n * check style guide compliance on target:    make vale TARGET=* \n * check metrics for documentation:           make allmetrics \n * other possible targets:                    make <TAB twice> \n ------------------------------------------------------------- \n
```

After:
```
kernel-docs/docs ❯ make

 ------------------------------------------------------------- 
 * watch, build and serve the documentation:  make run 
 * only build:                                make html 
 * only serve:                                make serve 
 * clean built doc files:                     make clean-doc 
 * clean full environment:                    make clean 
 * check links:                               make linkcheck 
 * check spelling:                            make spelling 
 * check spelling (without building again):   make spellcheck 
 * check inclusive language:                  make woke 
 * check accessibility:                       make pa11y 
 * check style guide compliance:              make vale 
 * check style guide compliance on target:    make vale TARGET=* 
 * check metrics for documentation:           make allmetrics 
 * other possible targets:                    make <TAB twice> 
 -------------------------------------------------------------
```

### CODE REVIEW

**Comment by Cypresslin** [comment]
Hmm I didn't see this issue on a Jammy system. I got the well-formatted output after running make.

**Comment by AnneCYH** [comment]
Hi @Cypresslin , thanks for checking on Jammy!

Same; I don't see any formatting issues on Noble.

@benjamin051000 are you using a specific editor terminal when you run `make`?

**Comment by benjamin051000** [comment]
Aha! Figured it out.

On Jammy, I get the same thing as you all:
```
❯ strace -fe execve make
execve("/usr/bin/make", ["make"], 0x7ffd4740c160 /* 34 vars */) = 0
strace: Process 255729 attached
[pid 255729] execve("/bin/sh", ["/bin/sh", "-c", "echo -e \"\\n\" \\\n        \"--------"...], 0x6551cb663930 /* 39 vars */) = 0
-e 
 ------------------------------------------------------------- 
 * watch, build and serve the documentation:  make run 
 * only build:                                make html 
 * only serve:                                make serve 
 * clean built doc files:                     make clean-doc 
 * clean full environment:                    make clean 
 * check links:                               make linkcheck 
 * check spelling:                            make spelling 
 * check spelling (without building again):   make spellcheck 
 * check inclusive language:                  make woke 
 * check accessibility:                       make pa11y 
 * check style guide compliance:              make vale 
 * check style guide compliance on target:    make vale TARGET=* 
 * check metrics for documentation:           make allmetrics 
 * other possible targets:                    make <TAB twice> 
 ------------------------------------------------------------- 

[pid 255729] +++ exited with 0 +++
+++ exited with 0 +++
```

_Looks like GNU make is calling `sh` to run `echo`, weird. I guess I expected it to use a builtin print method._

On Ubuntu (6.10+, see below), `file $(which sh)` is a symlink `dash`. On my desktop (openSUSE Tumbleweed), it's a symlink to `bash`. That's why my desktop is encountering this issue: Since it runs bash, it needs the `-e` flag to escape the newlines, but on Ubuntu `-e` is not needed.

I understand openSUSE is not a supported distro for this project, so I'm happy to close this PR.

However, I'm definitely curious if there's a way to make this more portable... people seem to be complaining about the portability of `echo` [here](https://unix.stackexchange.com/questions/700675/why-is-echo-e-behaving-weird-in-a-makefile) and recommend `printf` instead, or write `SHELL = bash` at the top of the makefile.  🤷🏼‍♂️  I'm not necessarily suggesting that this is something we _should_ do, I'm just exploring for learning's sake.

...And look at that, we've got an article why Ubuntu uses dash instead of bash: https://wiki.ubuntu.com/DashAsBinSh

**Comment by benjamin051000** [comment]
Closing for now. We can discuss portability at a later time if we decide it's worth looking in to.

**Comment by AnneCYH** [comment]
Hi @benjamin051000 , a note on the portability.

The Canonical documentation starter pack isn't meant to be used on Ubuntu _only_; in theory it's meant to be a base documentation project for anyone who might want to use Sphinx & Read the Docs, and use Canonical's project as a template. We do test some basic testing on Windows (not sure about macOS) and (obviously) most testing is done on Ubuntu. But it shouldn't be restricted to a specific distribution.

So if there are improvements that can be done, I strongly recommend proposing those changes in the starter pack itself so it trickles down to all repositories (eventually).
https://github.com/canonical/sphinx-docs-starter-pack

Lemme know if you have any further feedback on this; thanks!

**Pull request closed without merging**
